[project]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
description = "LightGBM Python Package"
maintainers = [
  {name = "Yu Shi", email = "yushi@microsoft.com"}
]
name = "lightgbm"

# TODO: make this dynamic, or maybe template it through?
version = "4.0.0"

[project.urls]
repository = "https://github.com/microsoft/LightGBM.git"

[build-system]

requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

# based on https://github.com/scikit-build/scikit-build-core#configuration
[tool.scikit-build]

cmake.minimum-version = "3.15"
ninja.minimum-version = "1.5"
ninja.make-fallback = true
cmake.args = []
cmake.verbose = true
cmake.build-type = "Release"
logging.level = "DEBUG"
sdist.reproducible = true
wheel.py-api = "py3"
experimental = true
strict-config = true
minimum-version = "0.1.5"
